version: '3.3'

services:
#Definimos el servicio Web, en este caso Odoo
  web:
    #Indicamos que imagen de Docker Hub utilizaremos
    image: vif30/odoo:v2
    #Indicamos que depende de "db", por lo cual debe ser procesada primero "db"
    depends_on:
        - db

    # Port Mapping: indicamos que el puerto 8069 del contenedor se mapeara con el mismo puerto en el anfritrion
    # Permitiendo acceder a Odoo mediante http://localhost:8069
    ports:
      - 8069:8069

    # Mapeamos el directorio de los contenedores (como por ejemplo" /mnt/extra-addons" )
    # en un directorio local (como por ejemplo en un directorio "./volumesOdoo/addons")
    # situado en el lugar donde ejecutemos "Docker compose"
    volumes:
      - ./volumesPug/addons:/mnt/extra-addons
      - ./volumesPug/odoo/filestore:/var/lib/odoo/filestore
      - ./volumesPug/odoo/sessions:/var/lib/odoo/sessions
    #Indicamos que el contenedor funcionara con usuario root y no con usuario odoo
    user: root
    # Definimos variables de entorno de Odoo
    environment:
      - HOST=db
      - USER=Moe
      - PASSWORD=Moe
    # Indica que pasa ese parametro al arrancar el servicio Odoo
    command: --dev=all 
#Definimos el servicio de la base de datos
  db:
    image: vif30/postgres:v2

    # Definimos variables de entorno de PostgreSQL
    environment:
      - POSTGRES_PASSWORD=Moe
      - POSTGRES_USER=Moe
      - POSTGRES_DB=postgres
    # Mapeamos el directorio del contenedor "var/lib/postgresql/data" en un directorio "./volumesOdoo/dataPostgreSQL"
    # situado en el lugar donde ejecutemos "Docker compose"
    volumes:
      - ./volumesPug/dataPostgreSQL:/var/lib/postgresql/data
